// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhbqrykpwhlgbilfrtkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYnFyeWtwd2hsZ2JpbGZydGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxOTEwNzUsImV4cCI6MjA2Mjc2NzA3NX0.VL-68hwtiV4nFuGtsz4e-F17lkcob2U95245U1vFMf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);